### ISSUE TITLE
Fix unicode issues

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/staging.sciml.ai#5]
They are seen in https://silly-wilson-497eb3.netlify.app/menu8/

**Comment by tlienart** [comment]
so just FYI the issue is that URLs are not escaped by Julia's basic Markdown --> html conversion. The safe way to do this is to url encode these. I will eventually provide this natively in Franklin.

**Comment by tlienart** [comment]
ok so it's actually dumber than the above, just when copy pasting you should be careful to copy paste the HTML code not the rendered stuff otherwise characters like `'` might not be pasted properly (this is not due to Franklin).

For future refs, the easiest is to 

1. copy paste the raw HTML 
1. look for `<li><a href=\"(.*?)\">(.*?)</a></li>` and replace with `- [$2]($1)` 

(that's what I just did)
